### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by zneu** [peterokagey/circle-games#7]
When a number is added to the game, tell the player what additional numbers it needs to be touching (up to the highest number on the board). It gets hard to keep track of all the potential connections that need to be made--unless, of course, you're trying to make this game exceptionally tricky!

**Comment by zneu** [comment]
If you make the board too small horizontally, you cannot make the board smaller vertically.

**Comment by peterokagey** [comment]
<img width="846" alt="screen shot 2017-02-05 at 11 50 55 am" src="https://cloud.githubusercontent.com/assets/10198714/22629368/6bccc062-eb99-11e6-9b22-a03729f29364.png">
 Open up the connections pane, and you can see a matrix of which connections still need to be made.
